name: IPCheckur
version: '1.0'
main: sxla.IPCheckur.Main
api-version: '1.21'
authors: [SimonXLAtticus]
description: Get User IP & GeoIP Info
commands:
  ip:
    usage: /ip <ID>
    permission: getipregion.use
  geoip:
    usage: /geoip <ID>
    permission: getipregion.geo
permissions:
  getipregion.use:
    default: op
  getipregion.geo:
    default: op